import { readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { ASTRO_DECLARATION } from '../src/adapters/astro.js';
import { BOOTSTRAP_DECLARATION } from '../src/adapters/bootstrap.js';
import {
  assertRequiredRoles,
  composedRouter,
  planManifest,
  resolveWithAdapters,
} from '../src/adapters/bridge.js';
import { CLIENT_ROUTE_FALLBACK_DECLARATION } from '../src/adapters/client-route-fallback.js';
import { MUI_DECLARATION } from '../src/adapters/mui.js';
import { NOT_FOUND_DECLARATION } from '../src/adapters/not-found.js';
import { REACT_DECLARATION } from '../src/adapters/react.js';
import { REACT_ROUTER_DECLARATION } from '../src/adapters/react-router.js';
import { createAdapterRegistry } from '../src/adapters/registry.js';
import { resolveProject, selectAdapters } from '../src/adapters/selection.js';
import { VITE_DECLARATION } from '../src/adapters/vite.js';
import {
  CATCH_ALL_ORDER,
  CLIENT_ROUTE_FALLBACK_GUARANTEES,
  CLIENT_ROUTE_FALLBACK_OUT_OF_SCOPE,
  resolveClientRouteFallbackContract,
  serialiseClientRouteFallbackContract,
} from '../src/domain/client-route-fallback.js';
import type { Contribution } from '../src/domain/contributions.js';
import { emptyContribution } from '../src/domain/contributions.js';
import type {
  AdapterDeclaration,
  FeatureId,
  ProjectManifest,
  RouterId,
  StylingId,
  UiLibraryId,
} from '../src/domain/index.js';
import { evaluateCombination } from '../src/domain/index.js';
import { collectRoutes } from '../src/domain/route-composition.js';
import { CliError } from '../src/errors.js';
import { createRegistry, findTemplatesRoot } from '../src/templates/registry.js';
import { renderPlan, TEST_CWD } from './helpers.js';

/**
 * The client-side route fallback, and the distinction it exists to protect.
 *
 * Every other feature suite is mostly about what the feature does. This one is
 * mostly about what it is *not*, because the whole reason it is a separate
 * adapter rather than a relaxation of Stage 8 is a difference that is easy to
 * argue away and expensive to get wrong:
 *
 *     not-found            != client-route-fallback
 *     file-based-routing   != client-side-routing
 *
 * The first pair is a property of the response against a property of the
 * render. The second is what decides which projects may claim which. So the
 * sharpest tests here are the refusals - and the ones asserting that no
 * generated byte anywhere claims an HTTP 404.
 */

const TEMPLATES_ROOT = findTemplatesRoot(path.resolve(import.meta.dirname, '..', 'src'));
const v1Registry = createRegistry(TEMPLATES_ROOT);
const adapters = createAdapterRegistry(TEMPLATES_ROOT);

const react = (over: Partial<ProjectManifest> = {}): ProjectManifest => ({
  targetDir: path.join(TEST_CWD, 'acme-app'),
  projectName: 'acme-app',
  framework: 'react',
  buildTool: 'vite',
  language: 'ts',
  styling: 'tailwind',
  uiLibrary: 'none',
  router: 'react-router',
  architecture: 'react-standard',
  features: ['starter:full', 'client-route-fallback'],
  site: {
    name: 'Acme Ltd',
    url: 'https://acme.example',
    description: 'Bespoke widgets.',
    locale: 'en',
    author: null,
  },
  packageManager: 'npm',
  git: true,
  install: true,
  ...over,
});

const astro = (features: readonly FeatureId[]): ProjectManifest => ({
  ...react(),
  targetDir: path.join(TEST_CWD, 'acme-site'),
  projectName: 'acme-site',
  framework: 'astro',
  router: 'file-based',
  architecture: 'astro-standard',
  features,
});

const planFor = (over: Partial<ProjectManifest> = {}) =>
  planManifest(react(over), {
    registry: v1Registry,
    cliVersion: '9.9.9',
    generatedAt: '2026-01-01T00:00:00.000Z',
    mode: 'full',
  });

const fileAt = (target: string, over: Partial<ProjectManifest> = {}): string => {
  const operation = planFor(over).plan.operations.find((entry) => entry.path === target);
  return operation?.type === 'write' ? operation.content : '';
};

const contributionsOf = (over: Partial<ProjectManifest> = {}): readonly Contribution[] =>
  resolveWithAdapters(react(over), TEMPLATES_ROOT).contributions;

const fallbackContribution = (over: Partial<ProjectManifest> = {}): Contribution => {
  const found = contributionsOf(over).find(
    (contribution) => contribution.owner === 'feature:client-route-fallback',
  );
  if (found === undefined) throw new Error('the feature contributed nothing at all');
  return found;
};

/**
 * Source with its comments removed.
 *
 * Needed because the honest thing and the forbidden thing are spelled the same
 * way here: the generated view explains why it does *not* set a document title,
 * which means naming the hook it declines to call. An assertion about what the
 * component does has to read the code rather than the prose about the code.
 */
const withoutComments = (source: string): string =>
  source
    .replace(/\{\s*\/\*[\s\S]*?\*\/\s*\}/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '');

const requiredCapabilities = (declaration: AdapterDeclaration): readonly string[] =>
  declaration.requires.flatMap((entry) =>
    entry.kind === 'requires'
      ? [entry.capability]
      : entry.kind === 'requiresOneOf'
        ? [...entry.capabilities]
        : [],
  );

const refusalText = (manifest: ProjectManifest): string => {
  let error: CliError | undefined;
  try {
    resolveProject(manifest, adapters);
  } catch (thrown) {
    error = thrown as CliError;
  }
  expect(error, 'the combination was accepted').toBeInstanceOf(CliError);
  return `${error?.message ?? ''}\n${error?.hint ?? ''}`;
};

// ---------------------------------------------------------------------------
// The dimension
// ---------------------------------------------------------------------------

describe('the fallback is a feature, and a different one from not-found', () => {
  it('occupies the feature dimension', () => {
    expect(CLIENT_ROUTE_FALLBACK_DECLARATION.kind).toBe('feature');
    expect(CLIENT_ROUTE_FALLBACK_DECLARATION.id).toBe('client-route-fallback');
  });

  it('is addressable only as a feature', () => {
    expect(adapters.feature('client-route-fallback').declaration.id).toBe('client-route-fallback');
    expect(() => adapters.router('client-route-fallback' as never)).toThrow(CliError);
    expect(() => adapters.styling('client-route-fallback' as never)).toThrow(CliError);
    expect(() => adapters.uiLibrary('client-route-fallback' as never)).toThrow(CliError);
  });

  it('is one of the implemented features, beside not-found rather than instead of it', () => {
    expect(adapters.implementedFeatures()).toContain('client-route-fallback');
    expect(adapters.implementedFeatures()).toContain('not-found');
    expect(adapters.hasFeature('client-route-fallback')).toBe(true);
  });

  it('is a distinct id, declaration and requirement from not-found', () => {
    expect(CLIENT_ROUTE_FALLBACK_DECLARATION.id).not.toBe(NOT_FOUND_DECLARATION.id);
    expect(CLIENT_ROUTE_FALLBACK_DECLARATION.displayName).not.toBe(
      NOT_FOUND_DECLARATION.displayName,
    );
    expect(requiredCapabilities(CLIENT_ROUTE_FALLBACK_DECLARATION)).toEqual([
      'client-side-routing',
    ]);
    expect(requiredCapabilities(NOT_FOUND_DECLARATION)).toEqual(['file-based-routing']);
  });

  it('provides nothing, because nothing can meaningfully require it', () => {
    expect(CLIENT_ROUTE_FALLBACK_DECLARATION.provides).toEqual([]);
  });

  it('requires no styling system, UI library, build tool or language', () => {
    expect(requiredCapabilities(CLIENT_ROUTE_FALLBACK_DECLARATION)).not.toContain('vite-plugins');
    expect(requiredCapabilities(CLIENT_ROUTE_FALLBACK_DECLARATION)).not.toContain('typescript');
    expect(requiredCapabilities(CLIENT_ROUTE_FALLBACK_DECLARATION)).not.toContain(
      'composed-stylesheet',
    );
    expect(requiredCapabilities(CLIENT_ROUTE_FALLBACK_DECLARATION)).not.toContain('react-runtime');
  });
});

// ---------------------------------------------------------------------------
// The matrix. This is the section the stage exists for.
// ---------------------------------------------------------------------------

describe('the supported and refused combinations', () => {
  it('React + Vite + React Router + client-route-fallback is supported', () => {
    expect(() => resolveProject(react(), adapters)).not.toThrow();
  });

  it('React + Vite + React Router + not-found is refused', () => {
    const text = refusalText(react({ features: ['starter:full', 'not-found'] }));
    expect(text).toContain('file-based-routing');
    expect(text).toContain('Not-found page');
  });

  it('React + Vite + React Router + not-found + client-route-fallback is refused', () => {
    // The combination somebody will eventually ask for, reasoning that the
    // fallback "covers" the not-found requirement. It does not: one is a
    // response and the other is a render, and selecting a second feature never
    // satisfies the first one's capability.
    const text = refusalText(
      react({ features: ['starter:full', 'not-found', 'client-route-fallback'] }),
    );
    expect(text).toContain('file-based-routing');
  });

  it('the refusal of that pair names not-found, not the fallback', () => {
    const text = refusalText(
      react({ features: ['starter:full', 'not-found', 'client-route-fallback'] }),
    );
    // The refusal has to be about the requirement that is unmet, not about the
    // pair being selected together. Selecting the fallback is fine; what fails
    // is that nothing here provides file-based routing, and the report says so
    // while listing client-side-routing among what the stack *does* provide.
    expect(text).toContain('Not-found page requires file-based-routing');
    expect(text).not.toContain('Client-side route fallback requires');
    expect(text).toMatch(/provides:[^\n]*client-side-routing/);
  });

  it('React + Vite without a router is refused, naming the routing capability', () => {
    // React provides `spa-routing` on its own. That is navigation without a
    // reload, not a route table - so there is nothing for an unmatched address
    // to fail to match, and the view would be a component nothing renders.
    const text = refusalText(react({ router: 'none' as RouterId }));
    expect(text).toContain('client-side-routing');
    expect(text).toContain('Client-side route fallback');
    expect(REACT_DECLARATION.provides).toContain('spa-routing');
    expect(REACT_DECLARATION.provides).not.toContain('client-side-routing');
  });

  it('Astro + not-found is supported and Astro + the fallback is not', () => {
    // The mirror image, and the reason neither feature subsumes the other.
    expect(() => resolveProject(astro(['starter:full', 'not-found']), adapters)).not.toThrow();
    expect(refusalText(astro(['starter:full', 'client-route-fallback']))).toContain(
      'client-side-routing',
    );
    expect(ASTRO_DECLARATION.provides).toContain('file-based-routing');
    expect(ASTRO_DECLARATION.provides).not.toContain('client-side-routing');
  });

  it('the three-way distinction holds across all four feature selections', () => {
    const cases: readonly { features: FeatureId[]; astroOk: boolean; reactOk: boolean }[] = [
      { features: ['starter:full'], astroOk: true, reactOk: true },
      { features: ['starter:full', 'not-found'], astroOk: true, reactOk: false },
      { features: ['starter:full', 'client-route-fallback'], astroOk: false, reactOk: true },
      {
        features: ['starter:full', 'not-found', 'client-route-fallback'],
        astroOk: false,
        reactOk: false,
      },
    ];

    for (const entry of cases) {
      const label = entry.features.join(' + ');
      expect(
        (() => {
          try {
            resolveProject(astro(entry.features), adapters);
            return true;
          } catch {
            return false;
          }
        })(),
        `astro + ${label}`,
      ).toBe(entry.astroOk);
      expect(
        (() => {
          try {
            resolveProject(react({ features: entry.features }), adapters);
            return true;
          } catch {
            return false;
          }
        })(),
        `react + router + ${label}`,
      ).toBe(entry.reactOk);
    }
  });

  it('is indifferent to the styling system and the UI library', () => {
    for (const styling of ['tailwind', 'bootstrap'] as StylingId[]) {
      for (const uiLibrary of ['none', 'mui'] as UiLibraryId[]) {
        expect(() => resolveProject(react({ styling, uiLibrary }), adapters)).not.toThrow();
      }
    }
    expect(
      evaluateCombination([
        REACT_DECLARATION,
        VITE_DECLARATION,
        BOOTSTRAP_DECLARATION,
        MUI_DECLARATION,
        REACT_ROUTER_DECLARATION,
        CLIENT_ROUTE_FALLBACK_DECLARATION,
      ]).compatible,
    ).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Capability, never adapter identity
// ---------------------------------------------------------------------------

describe('the requirement is a capability, not React Router', () => {
  it('a hypothetical router that routes on the client satisfies it', () => {
    // The strongest available statement: the feature works with a router that
    // does not exist, has never been written, and that it cannot name.
    const hypothetical: AdapterDeclaration = {
      id: 'angular-router',
      kind: 'router',
      displayName: 'A router that is not React Router',
      provides: ['client-side-routing'],
      requires: [],
    };
    expect(evaluateCombination([hypothetical, CLIENT_ROUTE_FALLBACK_DECLARATION]).compatible).toBe(
      true,
    );
  });

  it('a hypothetical router with only spa-routing is refused, naming the capability', () => {
    const hypothetical: AdapterDeclaration = {
      id: 'angular-router',
      kind: 'router',
      displayName: 'A router that only avoids reloads',
      provides: ['spa-routing'],
      requires: [],
    };
    const report = evaluateCombination([hypothetical, CLIENT_ROUTE_FALLBACK_DECLARATION]);
    expect(report.compatible).toBe(false);
    expect(JSON.stringify(report)).toContain('client-side-routing');
  });

  it('file-based-routing does not satisfy it either, in either direction', () => {
    // Neither capability implies the other, and this is the assertion that
    // would fail if somebody made one of them provide the other for
    // convenience.
    const fileBased: AdapterDeclaration = {
      id: 'nextjs',
      kind: 'framework',
      displayName: 'routes by file',
      provides: ['file-based-routing'],
      requires: [],
    };
    expect(evaluateCombination([fileBased, CLIENT_ROUTE_FALLBACK_DECLARATION]).compatible).toBe(
      false,
    );

    const clientSide: AdapterDeclaration = {
      id: 'angular-router',
      kind: 'router',
      displayName: 'routes in the browser',
      provides: ['client-side-routing'],
      requires: [],
    };
    expect(evaluateCombination([clientSide, NOT_FOUND_DECLARATION]).compatible).toBe(false);
  });

  it('names no adapter anywhere in what it declares', () => {
    const declared = JSON.stringify(CLIENT_ROUTE_FALLBACK_DECLARATION);
    for (const name of ['react', 'vite', 'tailwind', 'bootstrap', 'mui', 'astro']) {
      expect(declared.toLowerCase(), `declaration mentions ${name}`).not.toContain(name);
    }
  });
});

// ---------------------------------------------------------------------------
// The contract
// ---------------------------------------------------------------------------

describe('the contract is explicit about what it will not claim', () => {
  const contract = resolveClientRouteFallbackContract();

  it('guarantees a rendered view and an ordered catch-all', () => {
    expect(contract.catchAllPath).toBe('*');
    expect(contract.guarantees).toContain('renders-fallback-view');
    expect(contract.guarantees).toContain('catch-all-route');
    expect(contract.guarantees).toContain('catch-all-is-last');
  });

  it('puts the HTTP status out of scope, in the contract rather than only in prose', () => {
    // The single most important assertion in this file. A future edit that
    // decides the feature "is really a 404 after all" has to delete this.
    expect(contract.outOfScope).toContain('http-404-status');
    expect(contract.outOfScope).toContain('crawler-visible-not-found');
    expect(contract.outOfScope).toContain('server-rendered-not-found');
    expect(contract.outOfScope).toContain('host-configuration');
  });

  it('guarantees nothing about status codes, servers or crawlers', () => {
    for (const guarantee of CLIENT_ROUTE_FALLBACK_GUARANTEES) {
      expect(guarantee).not.toMatch(/404|status|http|server|crawler/i);
    }
  });

  it('never lists the same claim as both guaranteed and out of scope', () => {
    const guaranteed = new Set<string>(CLIENT_ROUTE_FALLBACK_GUARANTEES);
    for (const excluded of CLIENT_ROUTE_FALLBACK_OUT_OF_SCOPE) {
      expect(guaranteed.has(excluded), `${excluded} is on both lists`).toBe(false);
    }
  });

  it('is pure and serialises in a fixed order', () => {
    expect(serialiseClientRouteFallbackContract(resolveClientRouteFallbackContract())).toBe(
      serialiseClientRouteFallbackContract(resolveClientRouteFallbackContract()),
    );
    expect(serialiseClientRouteFallbackContract(contract).indexOf('catchAllPath')).toBeLessThan(
      serialiseClientRouteFallbackContract(contract).indexOf('outOfScope'),
    );
  });
});

// ---------------------------------------------------------------------------
// Contributions
// ---------------------------------------------------------------------------

describe('what the feature contributes, and what it refuses to', () => {
  it('adds no dependency', () => {
    expect(fallbackContribution().dependencies).toEqual([]);
  });

  it('adds no script', () => {
    expect(fallbackContribution().scripts).toEqual([]);
  });

  it('adds no template layer and creates no directory of its own', () => {
    expect(fallbackContribution().templateLayers).toEqual([]);
    expect(fallbackContribution().directories).toEqual([]);
  });

  it('changes nothing in the generated package manifest', () => {
    expect(fileAt('package.json')).toBe(fileAt('package.json', { features: ['starter:full'] }));
  });

  it('changes nothing in the build configuration', () => {
    expect(fileAt('vite.config.ts')).toBe(fileAt('vite.config.ts', { features: ['starter:full'] }));
  });

  it('contributes exactly one route, and only to the router', () => {
    const config = fallbackContribution().config;
    expect(config).toHaveLength(1);
    expect(config[0]?.target).toBe('app.router');
    expect(config[0]?.at).toBe('routes');
  });

  it('contributes the catch-all at the order the contract states', () => {
    expect(fallbackContribution().config[0]?.value).toEqual({
      path: '*',
      element: { kind: 'component', importName: 'NotFoundPage', role: 'page.notFound' },
      order: CATCH_ALL_ORDER,
    });
  });

  it('requests its view as a semantic role, never as a path', () => {
    const files = fallbackContribution().files;
    expect(files).toHaveLength(1);
    expect(files[0]?.target).toEqual({ kind: 'role', role: 'page.notFound' });
  });

  it('lets the architecture decide where the view lives', () => {
    const paths = planFor().plan.operations.map((operation) => operation.path);
    expect(paths).toContain('src/pages/NotFoundPage.tsx');
    expect(paths).not.toContain('src/pages/NotFoundPage.tsx'.replace('pages', 'views'));
  });

  it('contributes nothing at all when it is not selected', () => {
    const owners = contributionsOf({ features: ['starter:full'] }).map(
      (contribution) => contribution.owner,
    );
    expect(owners).not.toContain('feature:client-route-fallback');
    expect(
      planFor({ features: ['starter:full'] }).plan.operations.map((o) => o.path),
    ).not.toContain('src/pages/NotFoundPage.tsx');
  });
});

// ---------------------------------------------------------------------------
// The guarantee
// ---------------------------------------------------------------------------

describe('the guarantee is load-bearing', () => {
  it('requires the not-found role and the plan produces it', () => {
    const resolved = resolveWithAdapters(react(), TEMPLATES_ROOT);
    expect(resolved.project.requiredRoles).toContain('page.notFound');
    expect(() => assertRequiredRoles(resolved.project, planFor().plan.operations)).not.toThrow();
  });

  it('fails before writing when nothing produces the view', () => {
    const resolved = resolveWithAdapters(react(), TEMPLATES_ROOT);
    const withoutView = planFor().plan.operations.filter(
      (operation) => operation.path !== 'src/pages/NotFoundPage.tsx',
    );
    expect(() => assertRequiredRoles(resolved.project, withoutView)).toThrow(CliError);
  });

  it('requires no such role when the feature is absent', () => {
    expect(
      resolveWithAdapters(react({ features: ['starter:full'] }), TEMPLATES_ROOT).project
        .requiredRoles,
    ).not.toContain('page.notFound');
  });
});

// ---------------------------------------------------------------------------
// Composition with the router
// ---------------------------------------------------------------------------

describe('the route table composes rather than being edited', () => {
  const router = () => fileAt('src/routes/AppRouter.tsx');

  it('holds both routes, with the catch-all after the home route', () => {
    const source = router();
    expect(source).toContain('<Route path="/" element={children} />');
    expect(source).toContain('<Route path="*" element={<NotFoundPage />} />');
    expect(source.indexOf('path="/"')).toBeLessThan(source.indexOf('path="*"'));
  });

  it('imports the view by the path the architecture resolved', () => {
    expect(router()).toContain("import { NotFoundPage } from '../pages/NotFoundPage';");
  });

  it('records both owners, so neither adapter edited the other', () => {
    const operation = planFor().plan.operations.find(
      (entry) => entry.path === 'src/routes/AppRouter.tsx',
    );
    expect(operation?.origin).toContain('router:react-router');
    expect(operation?.origin).toContain('feature:client-route-fallback');
  });

  it('emits no catch-all when the feature is not selected', () => {
    // Matched against the JSX rather than the whole file: the routerless
    // version documents what a catch-all would buy, and that prose quotes
    // `path="*"` while emitting no such route.
    const source = fileAt('src/routes/AppRouter.tsx', { features: ['starter:full'] });
    expect(source).not.toContain('<Route path="*"');
    expect(source).not.toContain('NotFoundPage');
  });

  it('sorts the catch-all last however the contributions arrive', () => {
    // Order is declared, not incidental. Reversing the contribution list must
    // not reverse the table - if it did, a catch-all could end up above the
    // home route and swallow it.
    const config = contributionsOf().flatMap((contribution) => contribution.config);
    const forwards = collectRoutes(config, 'app.router', 'routes');
    const backwards = collectRoutes([...config].reverse(), 'app.router', 'routes');
    expect(forwards.map((claim) => claim.entry.path)).toEqual(['/', '*']);
    expect(backwards.map((claim) => claim.entry.path)).toEqual(['/', '*']);
  });

  it('would place a lower-ordered catch-all first, which is why the order is high', () => {
    // Proves the ordering is doing work rather than coinciding with insertion.
    const config = contributionsOf().flatMap((contribution) => contribution.config);
    const sabotaged = config.map((contribution) =>
      contribution.at === 'routes' && (contribution.value as { path?: string }).path === '*'
        ? { ...contribution, value: { ...(contribution.value as object), order: -1 } }
        : contribution,
    );
    expect(
      collectRoutes(sabotaged, 'app.router', 'routes').map((claim) => claim.entry.path),
    ).toEqual(['*', '/']);
    expect(CATCH_ALL_ORDER).toBeGreaterThan(0);
  });

  it('leaves every other wrapper outside the router, so it covers both routes', () => {
    /*
     * The defect this stage found, and the reason the router's order changed.
     *
     * The page a router wrapper is handed becomes one route's element. So a
     * wrapper nested *inside* the router wraps that route alone, and every
     * other route renders outside it. With MUI selected, the fallback rendered
     * with no theme, no baseline and no styling engine while the home page had
     * all three - and nothing failed, which is what made it worth a test.
     *
     * Asserted structurally rather than by naming MUI: any wrapper, present or
     * future, has to close after the router closes.
     */
    const root = fileAt('src/App.tsx', { uiLibrary: 'mui' as UiLibraryId });
    const open = [...root.matchAll(/<([A-Z][A-Za-z]*)>/g)].map((match) => match[1]!);
    expect(open).toContain('AppRouter');
    expect(open.at(-1)).toBe('AppRouter');
    expect(open.indexOf('AppProviders')).toBeLessThan(open.indexOf('AppRouter'));
  });

  it('refuses a second adapter claiming the same catch-all differently', () => {
    const config = contributionsOf().flatMap((contribution) => contribution.config);
    const rival: Contribution = {
      ...emptyContribution('feature:rival'),
      config: [
        {
          target: 'app.router',
          at: 'routes',
          value: {
            path: '*',
            element: { kind: 'component', importName: 'Other', role: 'page.notFound' },
            order: CATCH_ALL_ORDER,
          },
          owner: 'feature:rival',
          reason: 'a second view for the same address',
        },
      ],
    };
    expect(() => collectRoutes([...config, ...rival.config], 'app.router', 'routes')).toThrow(
      /both want to render "\*"/,
    );
  });

  it('refuses a route whose component role the architecture does not map', () => {
    const { project } = resolveWithAdapters(react(), TEMPLATES_ROOT);
    const homeless: Contribution = {
      ...emptyContribution('feature:nowhere'),
      config: [
        {
          target: 'app.router',
          at: 'routes',
          value: {
            path: '/nowhere',
            element: { kind: 'component', importName: 'Nowhere', role: 'config.framework' },
            order: 5,
          },
          owner: 'feature:nowhere',
          reason: 'a route the architecture cannot place',
        },
      ],
    };
    expect(() => composedRouter(project, [...contributionsOf(), homeless])).toThrow(
      /maps no "config\.framework" role/,
    );
  });
});

// ---------------------------------------------------------------------------
// Honesty about the response. The point of the whole stage.
// ---------------------------------------------------------------------------

describe('nothing generated claims an HTTP 404', () => {
  const generated = (over: Partial<ProjectManifest> = {}): readonly [string, string][] =>
    planFor(over).plan.operations.flatMap((operation) =>
      operation.type === 'write' ? [[operation.path, operation.content] as const] : [],
    );

  it('no generated file claims to send, set or return a 404 status', () => {
    for (const [file, content] of generated()) {
      expect(content, `${file} claims to produce a status`).not.toMatch(
        /(?:status|statusCode|res\.status|sendStatus|response)\s*[:=(]\s*['"`]?404/i,
      );
    }
  });

  it('the view says plainly that the response is not a 404', () => {
    const view = fileAt('src/pages/NotFoundPage.tsx');
    expect(view).toContain('200');
    expect(view).toMatch(/soft 404/);
    expect(view).toMatch(/not a response|component, not a response/);
  });

  it('the router says the same thing, so the caveat survives deleting either file', () => {
    const source = fileAt('src/routes/AppRouter.tsx');
    expect(source).toMatch(/usually a 200/);
    expect(source).toMatch(/not a 404/);
  });

  it('the caveat is present whether or not the feature is selected', () => {
    // Without the feature the router explains what a catch-all would and would
    // not buy; with it, the same caveat about the same catch-all. A reader must
    // not have to select the feature to learn the limitation.
    for (const features of [['starter:full'], ['starter:full', 'client-route-fallback']]) {
      const source = fileAt('src/routes/AppRouter.tsx', { features: features as FeatureId[] });
      expect(source, features.join('+')).toMatch(/not a 404/);
    }
  });

  it('the view fabricates no metadata, ARIA label or alt text', () => {
    // The generator has no truthful source for what a page nobody asked for
    // should say about itself, so it says nothing about it.
    const view = withoutComments(fileAt('src/pages/NotFoundPage.tsx'));
    expect(view).not.toContain('useDocumentMeta');
    expect(view).not.toContain('aria-label');
    expect(view).not.toContain('alt=');
    expect(view).not.toContain('<meta');
    expect(view).not.toContain('canonical');
    expect(view).not.toContain('robots');
  });
});

// ---------------------------------------------------------------------------
// The view itself
// ---------------------------------------------------------------------------

describe('the generated view', () => {
  const view = () => fileAt('src/pages/NotFoundPage.tsx');

  it('has exactly one primary heading', () => {
    expect([...view().matchAll(/<h1[\s>]/g)]).toHaveLength(1);
  });

  it('renders inside the shared layout, so it gets the main landmark', () => {
    expect(view()).toContain('<BaseLayout>');
    expect(fileAt('src/layouts/BaseLayout.tsx')).toContain('<main id="main"');
  });

  it('offers a keyboard-reachable link back to the site root', () => {
    // A real anchor with a real href: reachable by tab, activated by Enter, and
    // working with JavaScript disabled. A div with an onClick would satisfy a
    // click-based test and none of that.
    expect(view()).toMatch(/<a href="\/"/);
    expect(view()).not.toContain('onClick');
    expect(view()).not.toContain('role="button"');
  });

  it('names no styling system, and uses only classes both stylesheets define', () => {
    const source = view();
    for (const name of ['tailwind', 'bootstrap', 'bg-', 'btn-primary', 'container-fluid']) {
      expect(source.toLowerCase(), `the view mentions ${name}`).not.toContain(name);
    }

    const tailwind = readFileSync(
      path.join(TEMPLATES_ROOT, 'styling', 'tailwind', 'styles.global.css'),
      'utf8',
    );
    const bootstrap = readFileSync(
      path.join(TEMPLATES_ROOT, 'styling', 'bootstrap', 'styles.global.css'),
      'utf8',
    );
    const used = [...source.matchAll(/className="([^"{]+)"/g)].flatMap((match) =>
      match[1]!.split(/\s+/).filter(Boolean),
    );
    expect(used.length).toBeGreaterThan(0);
    for (const className of used) {
      expect(tailwind, `tailwind defines no .${className}`).toContain(`.${className}`);
      expect(bootstrap, `bootstrap defines no .${className}`).toContain(`.${className}`);
    }
  });

  it('names no router package, so a different router would need no edit', () => {
    expect(view()).not.toContain('react-router');
    expect(view()).not.toContain('<Link');
  });

  it('is byte-identical whichever styling system or UI library is selected', () => {
    const variants = [
      view(),
      fileAt('src/pages/NotFoundPage.tsx', { styling: 'bootstrap' as StylingId }),
      fileAt('src/pages/NotFoundPage.tsx', { uiLibrary: 'mui' as UiLibraryId }),
    ];
    expect(new Set(variants).size).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Structural isolation
// ---------------------------------------------------------------------------

describe('the adapter stays inside the contract', () => {
  const source = readFileSync(
    path.resolve(import.meta.dirname, '..', 'src', 'adapters', 'client-route-fallback.ts'),
    'utf8',
  );

  it('touches no filesystem, process, shell or network API', () => {
    for (const forbidden of [
      'node:fs',
      'node:child_process',
      'node:process',
      'readFileSync',
      'writeFileSync',
      'execSync',
      'spawn',
      'fetch(',
    ]) {
      expect(source, `the adapter uses ${forbidden}`).not.toContain(forbidden);
    }
  });

  it('imports no other adapter', () => {
    const imports = [...source.matchAll(/^import[^;]*from '([^']+)';/gm)].map((match) => match[1]);
    for (const specifier of imports) {
      expect(specifier, `the adapter imports ${specifier}`).not.toMatch(
        /\.\/(react|react-router|vite|tailwind|bootstrap|astro|mui|not-found)\.js$/,
      );
    }
  });

  it('contains no concrete output path', () => {
    // Comments stripped first: the header explains what the adapter refuses to
    // learn, and it cannot do that without naming the path once.
    const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
    expect(code).not.toContain('src/pages');
    expect(code).not.toContain('src/routes');
    // Its own template's filename is fair game - that file is the adapter's,
    // shipped in the adapter's own directory. Where it *lands* is not.
    expect(code).toContain("'client-route-fallback'");
  });

  it('is a pure function of its inputs', () => {
    expect(JSON.stringify(fallbackContribution())).toBe(JSON.stringify(fallbackContribution()));
  });

  it('resolves identically whatever the rest of the manifest says', () => {
    const feature = adapters.feature('client-route-fallback');
    expect(feature.resolve(react())).toEqual(
      feature.resolve(react({ styling: 'bootstrap', uiLibrary: 'mui', language: 'ts' })),
    );
  });
});

// ---------------------------------------------------------------------------
// Nothing else moved
// ---------------------------------------------------------------------------

describe('the rest of the project is untouched', () => {
  it('every file except the router and the view is what it was without the feature', () => {
    const withFeature = new Map(
      planFor().plan.operations.flatMap((operation) =>
        operation.type === 'write' ? [[operation.path, operation.content] as const] : [],
      ),
    );
    const without = new Map(
      planFor({ features: ['starter:full'] }).plan.operations.flatMap((operation) =>
        operation.type === 'write' ? [[operation.path, operation.content] as const] : [],
      ),
    );

    const added: string[] = [];
    for (const [file, content] of withFeature) {
      if (!without.has(file)) {
        added.push(file);
        continue;
      }
      if (file === 'src/routes/AppRouter.tsx') continue;
      // Since Stage 14 the provenance file records which features were
      // selected, so it differs by exactly the name of this one. That is the
      // file's job; before then it reported every project as having none.
      if (file === '.client-site.json') {
        expect(content).toContain('client-route-fallback');
        expect(without.get(file)).not.toContain('client-route-fallback');
        continue;
      }
      expect(content, `${file} changed`).toBe(without.get(file));
    }
    expect(added).toEqual(['src/pages/NotFoundPage.tsx']);
  });

  it('Astro generates exactly what it did before', () => {
    const plan = (features: readonly FeatureId[]) =>
      renderPlan(
        planManifest(astro(features), {
          registry: v1Registry,
          cliVersion: '9.9.9',
          generatedAt: '2026-01-01T00:00:00.000Z',
          mode: 'full',
          templateId: 'astro-tailwind',
        }).plan,
        TEMPLATES_ROOT,
      );
    expect(plan(['starter:full'])).toBe(plan(['starter:full']));
  });

  it('the same manifest produces the same plan twice', () => {
    expect(renderPlan(planFor().plan, TEMPLATES_ROOT)).toBe(
      renderPlan(planFor().plan, TEMPLATES_ROOT),
    );
  });

  it('no generated content carries a machine value or an unresolved token', () => {
    for (const operation of planFor({ uiLibrary: 'mui' as UiLibraryId }).plan.operations) {
      if (operation.type !== 'write') continue;
      expect(operation.content).not.toContain(TEST_CWD);
      expect(operation.content).not.toContain('\r\n');
      expect(operation.content).not.toMatch(/\{\{\s*[a-zA-Z]/);
    }
  });
});

// ---------------------------------------------------------------------------
// Golden
// ---------------------------------------------------------------------------

describe('golden: React + Vite + React Router + client-route-fallback', () => {
  const scenarios: readonly {
    name: string;
    file: string;
    over: Partial<ProjectManifest>;
  }[] = [
    { name: 'with Tailwind', file: './golden/react-fallback.txt', over: {} },
    {
      name: 'with Bootstrap',
      file: './golden/react-fallback-bootstrap.txt',
      over: { styling: 'bootstrap' as StylingId },
    },
    {
      name: 'with a UI library',
      file: './golden/react-fallback-mui.txt',
      over: { uiLibrary: 'mui' as UiLibraryId },
    },
  ];

  for (const scenario of scenarios) {
    it(`golden: ${scenario.name}`, async () => {
      await expect(renderPlan(planFor(scenario.over).plan, TEMPLATES_ROOT)).toMatchFileSnapshot(
        scenario.file,
      );
    });
  }

  it('the three are genuinely different snapshots', () => {
    const rendered = scenarios.map((scenario) =>
      renderPlan(planFor(scenario.over).plan, TEMPLATES_ROOT),
    );
    expect(new Set(rendered).size).toBe(3);
  });

  it('each differs from the same stack without the feature', () => {
    for (const scenario of scenarios) {
      expect(renderPlan(planFor(scenario.over).plan, TEMPLATES_ROOT)).not.toBe(
        renderPlan(planFor({ ...scenario.over, features: ['starter:full'] }).plan, TEMPLATES_ROOT),
      );
    }
  });
});

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------

describe('selection', () => {
  it('selects the feature alongside the other dimensions', () => {
    expect(selectAdapters(react(), adapters).adapters.map((entry) => entry.ref)).toContain(
      'feature:client-route-fallback',
    );
  });

  it('de-duplicates a feature asked for twice', () => {
    const twice = selectAdapters(
      react({ features: ['starter:full', 'client-route-fallback', 'client-route-fallback'] }),
      adapters,
    ).adapters.filter((entry) => entry.ref === 'feature:client-route-fallback');
    expect(twice).toHaveLength(1);
  });

  it('produces the same plan whether the feature is listed once or twice', () => {
    expect(
      renderPlan(
        planFor({ features: ['starter:full', 'client-route-fallback', 'client-route-fallback'] })
          .plan,
        TEMPLATES_ROOT,
      ),
    ).toBe(renderPlan(planFor().plan, TEMPLATES_ROOT));
  });
});
