import type { ConfigContribution } from './contributions.js';
import { CliError } from '../errors.js';

/**
 * Composing a build-tool configuration file from several adapters.
 *
 * This is the first concrete use of `ConfigContribution`, which has existed
 * since Stage 1 with nothing consuming it. React forced the issue: a Vite
 * config needs `@vitejs/plugin-react` from the framework and
 * `@tailwindcss/vite` from the styling system, and neither adapter can see the
 * other. Putting both in a template file would make the React template hardcode
 * Tailwind and break the moment someone picks React without it.
 *
 * So the adapters each contribute a plugin entry, and this emits the file.
 * Nothing here knows what React or Tailwind are - it receives entries and
 * serialises them.
 *
 * ## Why this does not affect Astro
 *
 * Emission is driven by the `config.build` file role. Astro's architecture maps
 * no such role - its build configuration is `astro.config.mjs`, mapped to
 * `config.framework` - so no build config is composed for Astro and its
 * template keeps registering the Tailwind plugin itself, exactly as before.
 * That is a legacy arrangement rather than a design: when the template layer is
 * generalised, Astro moves onto this mechanism too.
 *
 * ## What this is not
 *
 * Not a general configuration engine, and not an AST. It emits one shape - a
 * module that imports some plugins and exports a `defineConfig` call - because
 * that is the shape Vite config has. A second build tool with a different shape
 * gets its own emitter; the *mechanism* of contributing entries is what
 * generalises, not this function.
 */

/** One plugin an adapter wants registered in the build configuration. */
export interface BuildPluginEntry {
  /** Local binding, e.g. `react`. */
  readonly importName: string;
  /** Module specifier, e.g. `@vitejs/plugin-react`. */
  readonly importFrom: string;
  /** The expression placed in the plugins array, e.g. `react()`. */
  readonly call: string;
}

function isPluginEntry(value: unknown): value is BuildPluginEntry {
  if (typeof value !== 'object' || value === null) return false;
  const entry = value as Record<string, unknown>;
  return (
    typeof entry['importName'] === 'string' &&
    typeof entry['importFrom'] === 'string' &&
    typeof entry['call'] === 'string'
  );
}

/**
 * Collects plugin entries aimed at the build config, in a deterministic order.
 *
 * Sorted by owner. That is stable and, as it happens, puts the framework's
 * plugin ahead of the styling system's, which is the conventional order for
 * Vite. It is stability rather than semantics: an adapter that genuinely needs
 * to run before another has no way to say so yet, and would need an explicit
 * ordering field. No current combination needs one.
 */
export function collectBuildPlugins(
  contributions: readonly ConfigContribution[],
): readonly { readonly owner: string; readonly entry: BuildPluginEntry }[] {
  return contributions
    .filter(
      (contribution) => contribution.target === 'config.build' && contribution.at === 'plugins',
    )
    .map((contribution) => {
      if (!isPluginEntry(contribution.value)) {
        throw new CliError(`${contribution.owner} contributed an invalid build plugin entry.`, {
          hint: 'A plugin entry needs importName, importFrom and call, all strings.',
        });
      }
      return { owner: contribution.owner, entry: contribution.value };
    })
    .sort((a, b) => a.owner.localeCompare(b.owner));
}

/**
 * Emits a Vite configuration module.
 *
 * Deterministic: the same entries always produce the same bytes, LF-terminated
 * to match every other generated file.
 */
export function emitViteConfig(
  plugins: readonly { readonly owner: string; readonly entry: BuildPluginEntry }[],
): string {
  const imports = [
    "import { defineConfig } from 'vite';",
    ...plugins.map(({ entry }) => `import ${entry.importName} from '${entry.importFrom}';`),
  ];

  const calls = plugins.map(({ entry }) => `    ${entry.call},`);

  return [
    ...imports,
    '',
    '// Generated by create-clientkit. Each plugin below was contributed by the',
    '// adapter that needs it; add your own freely - this file is yours now.',
    'export default defineConfig({',
    '  plugins: [',
    ...calls,
    '  ],',
    '});',
    '',
  ].join('\n');
}
