import type { ConfigContribution } from './contributions.js';
import { CliError } from '../errors.js';

/**
 * Composing a build-tool configuration file from several adapters.
 *
 * This is the first concrete use of `ConfigContribution`, which has existed
 * since Stage 1 with nothing consuming it. React forced the issue: a Vite
 * config needs `@vitejs/plugin-react` from the framework and
 * `@tailwindcss/vite` from the styling system, and neither adapter can see the
 * other. Putting both in a template file would make the React template hardcode
 * Tailwind and break the moment someone picks React without it.
 *
 * So the adapters each contribute a plugin entry, and this emits the file.
 * Nothing here knows what React or Tailwind are - it receives entries and
 * serialises them.
 *
 * ## Why this does not affect Astro
 *
 * Emission is driven by the `config.build` file role. Astro's architecture maps
 * no such role - its build configuration is `astro.config.mjs`, mapped to
 * `config.framework` - so no build config is composed for Astro and its
 * template keeps registering the Tailwind plugin itself, exactly as before.
 * That is a legacy arrangement rather than a design: when the template layer is
 * generalised, Astro moves onto this mechanism too.
 *
 * ## What this is not
 *
 * Not a general configuration engine, and not an AST. It emits one shape - a
 * module that imports some plugins and exports a `defineConfig` call - because
 * that is the shape Vite config has. A second build tool with a different shape
 * gets its own emitter; the *mechanism* of contributing entries is what
 * generalises, not this function.
 */

/** One plugin an adapter wants registered in the build configuration. */
export interface BuildPluginEntry {
  /** Local binding, e.g. `react`. */
  readonly importName: string;
  /** Module specifier, e.g. `@vitejs/plugin-react`. */
  readonly importFrom: string;
  /** The expression placed in the plugins array, e.g. `react()`. */
  readonly call: string;
}

function isPluginEntry(value: unknown): value is BuildPluginEntry {
  if (typeof value !== 'object' || value === null) return false;
  const entry = value as Record<string, unknown>;
  return (
    typeof entry['importName'] === 'string' &&
    typeof entry['importFrom'] === 'string' &&
    typeof entry['call'] === 'string'
  );
}

/**
 * Compares by UTF-16 code unit rather than `localeCompare`.
 *
 * Generated bytes must not depend on the runtime's collation data, which
 * differs between a full-ICU Node and a small-ICU one. See the identical note
 * in `package-composition.ts`.
 */
function byCodeUnit(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * Collects plugin entries aimed at the build config, in a deterministic order.
 *
 * ## Ordering
 *
 * Sorted by owner, then by the local binding. That is stability rather than
 * semantics: it happens to put the framework's plugin ahead of the styling
 * system's, which is the conventional order for Vite, but nothing here knows
 * that.
 *
 * Stage 5 recorded that an adapter with a genuine ordering requirement has no
 * way to express one, and Stage 6 deliberately did not add it. `order` was
 * added to `ScriptContribution` in this same stage because there was a
 * demonstrated requirement - two adapters contribute scripts to one block and
 * the emitted order is part of the compatibility contract. No configuration
 * needs it: the two plugins in play are order-independent, and inventing a
 * field for a requirement nobody has would be machinery that cannot be
 * validated. When a real case appears, `order` is the shape to copy.
 *
 * ## Conflicts
 *
 * Two adapters contributing the same local binding for different modules would
 * emit a module with two clashing imports - invalid TypeScript, discovered at
 * build time in the user's project rather than here. Identical entries are
 * de-duplicated instead, because two adapters legitimately needing the same
 * plugin is cooperation, not a conflict.
 */
export function collectBuildPlugins(
  contributions: readonly ConfigContribution[],
): readonly { readonly owner: string; readonly entry: BuildPluginEntry }[] {
  const collected = contributions
    .filter(
      (contribution) => contribution.target === 'config.build' && contribution.at === 'plugins',
    )
    .map((contribution) => {
      if (!isPluginEntry(contribution.value)) {
        throw new CliError(`${contribution.owner} contributed an invalid build plugin entry.`, {
          hint: 'A plugin entry needs importName, importFrom and call, all strings.',
        });
      }
      return { owner: contribution.owner, entry: contribution.value };
    })
    .sort(
      (a, b) => byCodeUnit(a.owner, b.owner) || byCodeUnit(a.entry.importName, b.entry.importName),
    );

  const byBinding = new Map<string, { owner: string; entry: BuildPluginEntry }>();
  const result: { owner: string; entry: BuildPluginEntry }[] = [];

  for (const plugin of collected) {
    const seen = byBinding.get(plugin.entry.importName);
    if (seen === undefined) {
      byBinding.set(plugin.entry.importName, plugin);
      result.push(plugin);
      continue;
    }
    const identical =
      seen.entry.importFrom === plugin.entry.importFrom && seen.entry.call === plugin.entry.call;
    if (!identical) {
      throw new CliError(
        `Two adapters want to import "${plugin.entry.importName}" into the build configuration.`,
        {
          hint:
            `  ${seen.entry.importName} from '${seen.entry.importFrom}' as ${seen.entry.call}\n    owner: ${seen.owner}\n` +
            `  ${plugin.entry.importName} from '${plugin.entry.importFrom}' as ${plugin.entry.call}\n    owner: ${plugin.owner}\n` +
            'One of them must use a different local name.',
        },
      );
    }
    // Identical: already emitted once, and both owners genuinely wanted it.
  }

  return result;
}

/**
 * Emits a Vite configuration module.
 *
 * Deterministic: the same entries always produce the same bytes, LF-terminated
 * to match every other generated file.
 */
export function emitViteConfig(
  plugins: readonly { readonly owner: string; readonly entry: BuildPluginEntry }[],
): string {
  const imports = [
    "import { defineConfig } from 'vite';",
    ...plugins.map(({ entry }) => `import ${entry.importName} from '${entry.importFrom}';`),
  ];

  const calls = plugins.map(({ entry }) => `    ${entry.call},`);

  return [
    ...imports,
    '',
    '// Generated by create-clientkit. Each plugin below was contributed by the',
    '// adapter that needs it; add your own freely - this file is yours now.',
    'export default defineConfig({',
    '  plugins: [',
    ...calls,
    '  ],',
    '});',
    '',
  ].join('\n');
}
