import type {
  Contribution,
  DependencyContribution,
  DependencyKind,
  ScriptContribution,
} from './contributions.js';
import { CliError } from '../errors.js';

/**
 * Composing `package.json` from adapter contributions.
 *
 * ## The problem this solves
 *
 * Through Stage 5 the dependency and script contributions were *declarations*:
 * adapters returned them, tests asserted them, and the file that actually
 * reached the user was composed from template `_package.json` layers. Two
 * sources of truth, kept in step by hand. Stage 5's own notes recorded it as a
 * known limitation, and the failure mode is quiet - an adapter says it needs
 * `bootstrap@5.3.8`, the template ships `5.3.7`, everything passes, and the
 * generated project has neither what was declared nor an error.
 *
 * So the contributions became the source of truth and this composes them. The
 * templates keep only what no adapter can know: the project's own identity.
 *
 * ## What stays in the base
 *
 * `name`, `version`, `private`, `license`, `type`, `engines`, `keywords`. These
 * describe the generated project rather than any adapter's needs, and moving
 * them into the contribution system would mean inventing an owner for facts
 * that have none. The base is whatever the template layers produced, with the
 * three composed blocks removed and re-emitted from contributions - so a
 * template that adds a field keeps it, and a template that lists a dependency
 * finds it ignored.
 *
 * ## What this deliberately is not
 *
 * Not a merge DSL, not a semver resolver, not a package manager. It groups,
 * de-duplicates, sorts and rejects. Every case it cannot decide is an error
 * with provenance rather than a policy invented here - see `mergeDependencies`.
 *
 * Nothing in this file knows what React, Astro, Vite, Tailwind or Bootstrap
 * are. It receives contributions and returns an object.
 */

/** Where each dependency kind lands in `package.json`. */
const DEPENDENCY_FIELD: Readonly<Record<DependencyKind, string>> = {
  prod: 'dependencies',
  dev: 'devDependencies',
  peer: 'peerDependencies',
  optional: 'optionalDependencies',
};

/** Emission order of the composed blocks, appended after the base's own keys. */
const COMPOSED_FIELDS = [
  'scripts',
  'dependencies',
  'devDependencies',
  'peerDependencies',
  'optionalDependencies',
] as const;

/**
 * Compares by UTF-16 code unit rather than `localeCompare`.
 *
 * `localeCompare` consults the runtime's collation data, which differs between
 * a full-ICU Node and a small-ICU one and between platforms. Generated bytes
 * must not depend on that, so ordering here is defined by the string itself.
 */
function byCodeUnit(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** One package after merging, with every contributor retained. */
export interface ResolvedDependency {
  readonly name: string;
  readonly version: string;
  readonly kind: DependencyKind;
  /** Everyone who asked for it, sorted by owner. Provenance outlives the JSON. */
  readonly contributors: readonly DependencyContribution[];
}

/** One script after merging, with every contributor retained. */
export interface ResolvedScript {
  readonly name: string;
  readonly command: string;
  readonly order: number;
  readonly contributors: readonly ScriptContribution[];
}

export interface ComposedPackage {
  /** The finished manifest, ready to serialise. */
  readonly json: Record<string, unknown>;
  readonly dependencies: readonly ResolvedDependency[];
  readonly scripts: readonly ResolvedScript[];
}

function describe(entries: readonly { owner: string; reason: string; what: string }[]): string {
  return entries
    .map((entry) => `  ${entry.what}\n    owner: ${entry.owner}\n    reason: ${entry.reason}`)
    .join('\n');
}

/**
 * Merges dependency contributions, or refuses.
 *
 * Three cases, and only one of them is a merge:
 *
 *   - identical name, version and kind: one entry, every contributor recorded.
 *   - same name, different versions: an error. Choosing highest, lowest, first
 *     or last would all be defensible and all be silent, and a generator that
 *     silently picks a version produces projects nobody can reason about. The
 *     two adapters disagree about a fact; a person resolves that.
 *   - same name and version, different kind: also an error. `dev` and `prod`
 *     are not degrees of the same thing - one ships in the bundle and one does
 *     not. Promoting to `prod` would add weight the dev-only contributor never
 *     asked for; demoting to `dev` would break a runtime import. There is no
 *     rule in the existing model that says which wins, so this does not invent
 *     one.
 */
export function mergeDependencies(
  contributions: readonly DependencyContribution[],
): readonly ResolvedDependency[] {
  const byName = new Map<string, DependencyContribution[]>();
  for (const contribution of contributions) {
    const existing = byName.get(contribution.name);
    if (existing === undefined) byName.set(contribution.name, [contribution]);
    else existing.push(contribution);
  }

  const resolved: ResolvedDependency[] = [];

  for (const [name, entries] of byName) {
    const sorted = [...entries].sort(
      (a, b) => byCodeUnit(a.owner, b.owner) || byCodeUnit(a.version, b.version),
    );
    const first = sorted[0];
    // Unreachable: a map entry always holds at least the contribution that
    // created it. Narrowed rather than asserted so the types stay honest.
    if (first === undefined) continue;

    const versions = [...new Set(sorted.map((entry) => entry.version))];
    if (versions.length > 1) {
      throw new CliError(`Two adapters need different versions of "${name}".`, {
        hint: `${describe(
          sorted.map((entry) => ({
            owner: entry.owner,
            reason: entry.reason,
            what: `${entry.name}@${entry.version}`,
          })),
        )}\nPin both to the same version, or drop one of the adapters.`,
      });
    }

    const kinds = [...new Set(sorted.map((entry) => entry.kind))];
    if (kinds.length > 1) {
      throw new CliError(
        `Two adapters disagree about whether "${name}" is a runtime or development dependency.`,
        {
          hint: `${describe(
            sorted.map((entry) => ({
              owner: entry.owner,
              reason: entry.reason,
              what: `${entry.name}@${entry.version} as ${DEPENDENCY_FIELD[entry.kind]}`,
            })),
          )}\nOne of them is wrong about what the package is for; this is not something the generator can decide.`,
        },
      );
    }

    resolved.push({
      name,
      version: first.version,
      kind: first.kind,
      contributors: sorted,
    });
  }

  return resolved.sort((a, b) => byCodeUnit(a.name, b.name));
}

/**
 * Merges script contributions, or refuses.
 *
 * Same shape of decision as dependencies: identical commands de-duplicate and
 * keep both contributors, different commands under one name are an error. A
 * generator that silently picked one would produce a project whose `npm run
 * build` does something the adapter that asked for it never intended.
 */
export function mergeScripts(
  contributions: readonly ScriptContribution[],
): readonly ResolvedScript[] {
  const byName = new Map<string, ScriptContribution[]>();
  for (const contribution of contributions) {
    const existing = byName.get(contribution.name);
    if (existing === undefined) byName.set(contribution.name, [contribution]);
    else existing.push(contribution);
  }

  const resolved: ResolvedScript[] = [];

  for (const [name, entries] of byName) {
    const sorted = [...entries].sort((a, b) => byCodeUnit(a.owner, b.owner));
    const first = sorted[0];
    if (first === undefined) continue;

    const commands = [...new Set(sorted.map((entry) => entry.command))];
    if (commands.length > 1) {
      throw new CliError(`Two adapters want "${name}" to run different commands.`, {
        hint: `${describe(
          sorted.map((entry) => ({
            owner: entry.owner,
            reason: entry.reason,
            what: `${entry.name}: ${entry.command}`,
          })),
        )}\nRename one of them, or drop one of the adapters.`,
      });
    }

    resolved.push({
      name,
      command: first.command,
      // The lowest requested position wins, so an adapter cannot push another
      // adapter's script down the list by asking for a large number.
      order: Math.min(...sorted.map((entry) => entry.order)),
      contributors: sorted,
    });
  }

  return resolved.sort(
    (a, b) =>
      a.order - b.order ||
      byCodeUnit(a.contributors[0]?.owner ?? '', b.contributors[0]?.owner ?? '') ||
      byCodeUnit(a.name, b.name),
  );
}

/**
 * Produces the finished manifest.
 *
 * Key order is the base's own order first, then the composed blocks - which
 * reproduces the arrangement the templates have always had, so making
 * composition authoritative changed no generated bytes for the stacks that
 * already existed. An empty block is omitted rather than emitted as `{}`.
 */
export function composePackage(
  base: Record<string, unknown>,
  contributions: readonly Contribution[],
): ComposedPackage {
  const dependencies = mergeDependencies(
    contributions.flatMap((contribution) => contribution.dependencies),
  );
  const scripts = mergeScripts(contributions.flatMap((contribution) => contribution.scripts));

  const json: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(base)) {
    // The composed blocks are re-emitted below, in a fixed position. A template
    // that still lists one is not merged with the contributions - it is
    // ignored, which is what "the contributions are authoritative" means. A
    // drift test asserts no template relies on that.
    if ((COMPOSED_FIELDS as readonly string[]).includes(key)) continue;
    json[key] = value;
  }

  if (scripts.length > 0) {
    json['scripts'] = Object.fromEntries(scripts.map((entry) => [entry.name, entry.command]));
  }

  for (const kind of ['prod', 'dev', 'peer', 'optional'] as const) {
    const forKind = dependencies.filter((entry) => entry.kind === kind);
    if (forKind.length === 0) continue;
    json[DEPENDENCY_FIELD[kind]] = Object.fromEntries(
      forKind.map((entry) => [entry.name, entry.version]),
    );
  }

  return { json, dependencies, scripts };
}
