import { createHash } from 'node:crypto';
import { existsSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

import { comparePlanPaths, type FileOperation, type GenerationPlan } from './files.js';
import { PROVENANCE_FILE } from './provenance.js';

/**
 * A plan against what is already on disk: which planned files are missing,
 * which are already exactly what the plan would write, and which differ.
 *
 * ## What "the same" means
 *
 * Bytes. A `write` is compared with the content the plan carries, a `copy`
 * with its source file. There is no normalisation, no diff and no merge: a file
 * either is what ClientKit would write now, or it is not.
 *
 * `.client-site.json` is the one exception, because it records *when* and *by
 * which CLI* it was written. Two records that differ only in `generatedAt` and
 * `cliVersion` describe the same project, so the existing one counts as
 * unchanged - otherwise every re-run would rewrite the record for nothing.
 *
 * ## What it cannot tell
 *
 * Whether a differing file was edited by the developer or generated by an
 * earlier release or another configuration. ClientKit keeps no record of the
 * bytes it wrote, so all three look the same here, and every caller treats a
 * difference as something only a person may overwrite.
 *
 * Reads only the files the plan names, never the rest of the project. Writes
 * nothing.
 */

export interface PlanComparison {
  /** Planned files that do not exist yet. */
  readonly missing: readonly string[];
  /** Planned files that already hold exactly what the plan would write. */
  readonly unchanged: readonly string[];
  /** Planned files that exist with other content. */
  readonly differs: readonly string[];
  /**
   * Every planned path as it was when compared, from the same reads. The
   * executor is handed it and refuses to write if any of the paths it writes
   * has changed since (see `apply`).
   */
  readonly observed: TargetObservation;
}

/**
 * What one planned path held when ClientKit looked at it: nothing, something
 * that is not a file, or a file with exactly these bytes.
 */
export type Observed = 'absent' | 'not-a-file' | `sha256:${string}`;

/** Planned paths and what each held when the decision to write them was made. */
export type TargetObservation = ReadonlyMap<string, Observed>;

/** Read-only filesystem access, injectable for tests. */
export interface CompareFs {
  exists(file: string): boolean;
  isFile(file: string): boolean;
  read(file: string): Buffer;
}

export const realCompareFs: CompareFs = {
  exists: (file) => existsSync(file),
  isFile: (file) => {
    try {
      return statSync(file).isFile();
    } catch {
      return false;
    }
  },
  read: (file) => readFileSync(file),
};

/** The record's content, minus the two fields that say when and by what it was written. */
function recordIdentity(text: string): string | undefined {
  try {
    const parsed = JSON.parse(text) as Record<string, unknown>;
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return undefined;
    const { generatedAt: _when, cliVersion: _by, ...rest } = parsed;
    return JSON.stringify(rest);
  } catch {
    return undefined;
  }
}

function sameContent(operation: FileOperation, existing: Buffer, fs: CompareFs): boolean {
  if (operation.type === 'copy') return existing.equals(fs.read(operation.source));
  if (operation.path === PROVENANCE_FILE) {
    const planned = recordIdentity(operation.content);
    return planned !== undefined && planned === recordIdentity(existing.toString('utf8'));
  }
  return existing.equals(Buffer.from(operation.content, 'utf8'));
}

function fingerprint(bytes: Buffer): Observed {
  return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
}

export function comparePlan(plan: GenerationPlan, fs: CompareFs = realCompareFs): PlanComparison {
  const missing: string[] = [];
  const unchanged: string[] = [];
  const differs: string[] = [];
  const observed = new Map<string, Observed>();

  for (const operation of plan.operations) {
    const target = path.join(plan.targetDir, ...operation.path.split('/'));
    if (!fs.exists(target)) {
      missing.push(operation.path);
      observed.set(operation.path, 'absent');
    } else if (!fs.isFile(target)) {
      // A directory where the plan puts a file is a difference, never a match.
      differs.push(operation.path);
      observed.set(operation.path, 'not-a-file');
    } else {
      const existing = fs.read(target);
      observed.set(operation.path, fingerprint(existing));
      if (sameContent(operation, existing, fs)) unchanged.push(operation.path);
      else differs.push(operation.path);
    }
  }

  const sorted = (list: string[]) => list.sort(comparePlanPaths);
  return {
    missing: sorted(missing),
    unchanged: sorted(unchanged),
    differs: sorted(differs),
    observed,
  };
}

/** What a path holds now, in the terms of an observation. Reads; never writes. */
export function observePath(file: string, fs: CompareFs = realCompareFs): Observed {
  if (!fs.exists(file)) return 'absent';
  if (!fs.isFile(file)) return 'not-a-file';
  return fingerprint(fs.read(file));
}

/**
 * Every planned path as it is now, for a run that does not compare content -
 * a first generation, or one into a directory ClientKit did not generate.
 * Taken before the question is asked, so the executor can tell whether the
 * directory changed while a person was answering it.
 */
export function observeTarget(
  plan: GenerationPlan,
  fs: CompareFs = realCompareFs,
): TargetObservation {
  return new Map(
    plan.operations.map((operation) => [
      operation.path,
      observePath(path.join(plan.targetDir, ...operation.path.split('/')), fs),
    ]),
  );
}

/**
 * Files a plan would replace in an existing target: every planned path that
 * is already there. Drives the confirmation. Read-only, from an observation.
 */
export function findCollisions(
  plan: GenerationPlan,
  observed: TargetObservation = observeTarget(plan),
): string[] {
  return plan.operations
    .map((operation) => operation.path)
    .filter((relative) => (observed.get(relative) ?? 'absent') !== 'absent')
    .sort();
}

/**
 * The same plan, with only the operations for the given paths.
 *
 * Not a second plan: the operations, their order and their content are the
 * plan's own. It is how a re-run writes only what it decided to write, through
 * the same executor, instead of rewriting files that are already right.
 */
export function narrowPlan(plan: GenerationPlan, paths: Iterable<string>): GenerationPlan {
  const keep = new Set(paths);
  return { ...plan, operations: plan.operations.filter((operation) => keep.has(operation.path)) };
}
